addons:
  apt:
    packages:
      - git
      - make
      - curl

before_install:
  - echo "before_install"
  - mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin
  - curl https://releases.hashicorp.com/terraform/0.12.5/terraform_0.12.5_linux_amd64.zip > \
    terraform_0.12.5_linux_amd64.zip
  - unzip terraform_0.12.5_linux_amd64.zip -d {HOME}/bin

install:
  - echo "install"
  - make init

script:
  - echo "script"
  - terraform -v
  - make terraform:install
  - make terraform:get-plugins
  - make terraform:get-modules
  - make terraform:lint
  - make terraform:validate
